#!/bin/bash
echo "ai-business-document-designer loaded. Skills available:"
echo "  ai-business-document-brief        — Stage 1: discovery (output_type: pitch-deck-vc / pitch-deck-b2b / brochure / portfolio-personal / portfolio-agency / catalog / flyer / trifold; audience; ask/CTA; theme preset)"
echo "  ai-business-document-narrative    — Stage 2: narrative arc for decks + modular page layout for multi-page PDF (hook, tension, payoff, ask, pattern match, framework spine) — HUMAN APPROVAL GATE"
echo "  ai-business-document-copywriting  — Stage 3: per-page copy (headline <=10 words, sub-text <=25 words, CTA, pricing tier articulation, bilingual support) — HUMAN APPROVAL GATE"
echo "  ai-business-document-gen          — Stage 4: visual production (image prompts via GeminiGen.AI / Nano Banana Pro, Seedance 2.0 video, optional Remotion, HTML+CSS print stylesheet for PDF render, output-type-aware aspect ratio)"
echo "  ai-business-document-validate     — Stage 5: 100-point quality gate (Visual Ratio + Narrative/Framework Fit + CTA Clarity + Print Readiness + Anti-AI-Slop)"
echo ""
echo "Agent available:"
echo "  ai-business-document-agent — self-contained subagent for batch / variant production across formats"
echo ""
echo "REMINDER: Read references/global-config.md FIRST for any document work."
echo "REMINDER: Narrative/Layout + Copywriting are HARD GATES — no visual generation tokens spent until both approved."
echo "REMINDER: Visual ratio >= 70% mandatory per page. Hard-fail under 60%."
echo "REMINDER: Print outputs require CMYK + 3-5mm bleed + 300dpi + embedded fonts."
echo "REMINDER: Plugin migrated from pitch-deck-designer 2026-05-21 (scope expanded to multi-format business documents). Folder rename pending — file paths still use pitch-deck-designer/ until Ali manually renames."
