#!/bin/bash
# compile-references.sh
# Compiles per-skill reference bundles for split-pipeline injection.
# Mirrors the reference cheat sheet in CLAUDE.md.
#
# Usage:
#   ./compile-references.sh                                   # test mode: print map and exit 0
#   ./compile-references.sh --output-type deck-vc --theme indusia-tech
#   ./compile-references.sh --output-type brochure-product --theme indo-tropical

set -euo pipefail

# Resolve plugin root (one level up from scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REF_DIR="$PLUGIN_ROOT/references"
OUT_DIR="$REF_DIR/compiled"

# ---- Parse flags --------------------------------------------------------
OUTPUT_TYPE=""
THEME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-type) OUTPUT_TYPE="$2"; shift 2 ;;
    --theme)       THEME="$2";       shift 2 ;;
    -h|--help)
      grep -E '^# ' "$0" | head -20 | sed 's/^# //'
      exit 0
      ;;
    *) echo "Unknown flag: $1" >&2; exit 2 ;;
  esac
done

# ---- Skill -> reference map ---------------------------------------------
# Order = priority of injection. Conditional files noted with [cond].
declare -A SKILL_MAP
SKILL_MAP[brief]="global-config.md frameworks/<output_type>.md indonesian-context.md"
SKILL_MAP[narrative]="global-config.md storyline-frameworks.md investor-psychology.md layout-grammar.md frameworks/<output_type>.md"
SKILL_MAP[copywriting]="global-config.md copywriting-patterns.md business-model-patterns.md[cond:catalog|flyer|brochure] indonesian-context.md"
SKILL_MAP[gen]="global-config.md visual-language.md image-prompt-templates.md safety-filter-playbook.md themes/<theme>.md html-css-print-templates.md[cond:print] seedance-prompt-templates.md[cond:motion]"
SKILL_MAP[validate]="global-config.md scoring-rubric.md visual-language.md investor-psychology.md"

PRINT_TYPES="brochure-product portfolio-personal portfolio-agency catalog-product service-flyer trifold-leaflet"
PRICING_TYPES="catalog-product service-flyer brochure-product"

is_print_type() { echo "$PRINT_TYPES" | grep -wq "$1"; }
is_pricing_type() { echo "$PRICING_TYPES" | grep -wq "$1"; }

# ---- Test mode (no flags) -----------------------------------------------
if [[ -z "$OUTPUT_TYPE" && -z "$THEME" ]]; then
  echo "compile-references.sh — skill-to-reference map"
  echo "==============================================="
  for skill in brief narrative copywriting gen validate; do
    echo ""
    echo "[$skill]"
    echo "  ${SKILL_MAP[$skill]}" | tr ' ' '\n' | sed 's/^/    - /'
  done
  echo ""
  echo "Pass --output-type <slug> --theme <slug> to materialize bundles."
  exit 0
fi

if [[ -z "$OUTPUT_TYPE" || -z "$THEME" ]]; then
  echo "ERROR: both --output-type and --theme are required for materialize mode." >&2
  exit 2
fi

# ---- Idempotent setup ----------------------------------------------------
mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR"/refs-*.md

# ---- Bundle builder ------------------------------------------------------
build_bundle() {
  local skill="$1"
  local out_file="$OUT_DIR/refs-$skill.md"
  local refs="${SKILL_MAP[$skill]}"

  {
    echo "# Compiled reference bundle — skill: ai-business-document-$skill"
    echo ""
    echo "> Auto-generated by scripts/compile-references.sh"
    echo "> output_type: $OUTPUT_TYPE | theme: $THEME | generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
  } > "$out_file"

  for token in $refs; do
    # Strip conditional tag (after [cond:...]) and decide include/skip
    local path="${token%%[cond:*}"
    local cond="${token#*[cond:}"; cond="${cond%]}"

    if [[ "$token" == *"[cond:"* ]]; then
      case "$cond" in
        "catalog|flyer|brochure")
          is_pricing_type "$OUTPUT_TYPE" || continue ;;
        "print")
          is_print_type "$OUTPUT_TYPE" || continue ;;
        "motion")
          # Motion is operator-set; always include for gen stage (safe default).
          ;;
      esac
    fi

    # Substitute placeholders
    path="${path/<output_type>/$OUTPUT_TYPE}"
    path="${path/<theme>/$THEME}"

    local full_path="$REF_DIR/$path"
    if [[ ! -f "$full_path" ]]; then
      echo "## [MISSING] $path" >> "$out_file"
      echo "" >> "$out_file"
      echo "Reference file not found at \`references/$path\`. Skipped." >> "$out_file"
      echo "" >> "$out_file"
      continue
    fi

    {
      echo "---"
      echo ""
      echo "## SECTION: references/$path"
      echo ""
      cat "$full_path"
      echo ""
    } >> "$out_file"
  done

  echo "  wrote: $out_file ($(wc -l < "$out_file") lines)"
}

echo "Compiling reference bundles for output_type=$OUTPUT_TYPE theme=$THEME"
for skill in brief narrative copywriting gen validate; do
  build_bundle "$skill"
done

echo "Done. Bundles in: $OUT_DIR"
